### ISSUE TITLE
Please add our new paper to the repo, thanks!

### ISSUE THREAD

**Issue by Toytiny** [autodriving-heart/NeurIPS2024-Papers-about-Autonomous-Driving#1]
Paper title: RadarOcc: Robust 3D Occupancy Prediction with 4D
Imaging Radar
Paper link: https://arxiv.org/pdf/2405.14014
Code link: https://github.com/Toytiny/RadarOcc/

**Comment by loki369loki** [comment]
> Paper title: RadarOcc: Robust 3D Occupancy Prediction with 4D Imaging Radar Paper link: https://arxiv.org/pdf/2405.14014 Code link: https://github.com/Toytiny/RadarOcc/

Thank you for your attention. Your paper has been added to the list.
